security:
    basic:
      enabled: true
    user:
      name: '{cipher}4ca754ebea60484e9e1a5a480a7c7f68382e4a463d03a35b968f88335a5f33e2'
      password: '{cipher}78c8e4d3e081f1c395b2bff6c64b4366ad8b1dfaef67dfa04161f8546bd654160b18f8dfab574068d4b89004610adc78'

eureka:
  instance:
    securePort: ${server.port}
    securePortEnabled: true #访问eureka上注册的HTTPS服务, 貌似验证不通过
    nonSecurePortEnabled: false #访问eureka上注册的HTTPS服务, 貌似验证不通过
    #hostname: cloud.aqier.com #配置当前服务节点的 主机名, 公共配置不需要
    leaseExpirationDurationInSeconds: 6 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒, 这里设置6秒, 即快速响应, 服务一旦不可用立即移除
    leaseRenewalIntervalInSeconds: 2 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
    preferIpAddress: true
    #instanceId: ${spring.cloud.client.ipAddress}:${server.port} #与 preferIpAddress 二选一即可
    metadataMap: 
      hostname: ${server.hostname}
      securePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: https://${security.user.name}:${security.user.password}@172.31.26.217:8889/eureka/
    registerWithEureka: true #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true, 这里没有配置eureka地址, 不能启用
    fetchRegistry: true #此客户端是否获取eureka服务器注册表上的注册信息，默认为true

server: 
  tomcat: 
    maxThreads: 5
  ssl1: #启用HTTPS
    enabled: true
    keyStore: https://${spring.cloud.config.username}:${spring.cloud.config.password}@cloud.aqier.com:8888/getCert
    keyStorePassword: '{cipher}e804f4acd981cdc39a85a64abdd05a0a86058b74779f346c4696d891b75eaeddfe00f1b95b0485d574525fcfd61b745c85e476a22ae438528fd2a020350508a6'
    keyStoreType: PKCS12
    keyAlias: aqier

logger:
  level:
    root: INFO
    com.aqier: DEBUG
    org.mybatis: DEBUG

spring:
  datasource:
    port: 8887 #指定端口
    url: jdbc:h2:tcp://localhost:${spring.datasource.port}/~/aqier #jdbc:mysql://cloud.aqier.com:3306/aqier
    driverClassName: org.h2.Driver #com.mysql.jdbc.Driver
    username: '{cipher}cbb0b63f3112f18cc054d3a025e7db97d6fb9ecbec3af17234ec073707a8d6d0'
    password: '{cipher}7df73bc4bbbba33ebfcf14929a43b98b8dab75e2d954d159d051e24613b85ef4'
    maxIdle: 10
    maxWait: 3000
    minIdle: 5
    initialSize: 5
    validationQuery: SELECT 1
    testOnBorrow: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 18800
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    
  redis:
    host: cloud.aqier.com
    port: 6379
    password: '{cipher}7df73bc4bbbba33ebfcf14929a43b98b8dab75e2d954d159d051e24613b85ef4'
    timeout: 1800
        