gateway:
  timeout: 60000 #gateway超时时间公共变量

spring:
  cloud:
    loadbalancer:
      retry:
        enable: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul: #参见 org.springframework.cloud.netflix.zuul.filters.ZuulProperties
  ignoredPatterns: /health,/error
  retryable: false #是否重试
  ribbonIsolationStrategy: THREAD
  host:
    socketTimeoutMillis: ${gateway.timeout:60000}
    connectTimeoutMillis: ${gateway.timeout:60000}
  routes:
    system-manager:
      path: /system/**
      serviceId: AQIER-SYSTEM-MANAGER
    sso-server:
      path: /sso/**
      serviceId: AQIER-SSO-SERVER
    database-server:
      path: /database/**
      serviceId: AQIER-DATABASE-SERVER

ribbon:
  ReadTimeout: ${gateway.timeout:60000}
  ConnectTimeout: ${gateway.timeout:60000}
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false # 不启用重试后, MaxAutoRetries/MaxAutoRetriesNextServer 就没用了?
  IsSecure: true

hystrix:
  command:
    default:
      coreSize: 200 #并发执行的最大线程数，默认10
      maxQueueSize: 200 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 50 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
      execution:
        timeout:
          enabled: true #禁用网关超时时间
        isolation:
          thread:
            timeoutInMilliseconds: ${gateway.timeout:60000}
            ribbon:
              ReadTimeout: ${gateway.timeout:60000}
              ConnectTimeout: ${gateway.timeout:60000}
